apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-01-08T09:32:37Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":5000,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:name: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-expose
    operation: Update
    time: "2021-01-08T09:32:37Z"
  name: app-service
  namespace: default
  resourceVersion: "14672"
  selfLink: /api/v1/namespaces/default/services/app-service
  uid: 8dc9ffa3-3ecb-4711-a370-c339fb95ed54
spec:
  clusterIP: 10.152.183.176
  clusterIPs:
  - 10.152.183.176
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30898
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    name: app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
